 export const carMakesAndModels = {
  Toyota: ['Corolla', 'Camry', 'RAV4', 'Highlander', 'Tacoma'],
  Honda: ['Civic', 'Accord', 'CR-V', 'Pilot', 'Fit'],
  Ford: ['F-150', 'Mustang', 'Escape', 'Explorer', 'Fusion'],
  Chevrolet: ['Malibu', 'Silverado', 'Equinox', 'Tahoe', 'Camaro'],
  BMW: ['X5', '3 Series', '5 Series', 'X3', 'M3'],
  Audi: ['A4', 'A6', 'Q5', 'Q7', 'A8'],
  Mercedes: ['C-Class', 'E-Class', 'S-Class', 'GLC', 'GLE'],
  Nissan: ['Altima', 'Sentra', 'Maxima', 'Rogue', 'Pathfinder'],
  Volkswagen: ['Jetta', 'Golf', 'Passat', 'Tiguan', 'Atlas'],
  Hyundai: ['Sonata', 'Elantra', 'Santa Fe', 'Tucson', 'Kona'],
  Kia: ['Sorento', 'Sportage', 'Optima', 'Forte', 'Telluride'],
  Lexus: ['RX', 'ES', 'NX', 'GX', 'LS'],
  Subaru: ['Outback', 'Forester', 'Impreza', 'Legacy', 'Ascent'],
  Mazda: ['CX-5', 'Mazda3', 'Mazda6', 'CX-9', 'MX-5 Miata'],
  Porsche: ['911', 'Cayenne', 'Macan', 'Panamera', 'Taycan'],
  Jaguar: ['F-Type', 'XE', 'XF', 'XJ', 'F-Pace'],
  Tesla: ['Model S', 'Model 3', 'Model X', 'Model Y'],
  Chrysler: ['Pacifica', 'Charger', '300'],
  Dodge: ['Challenger', 'Charger', 'Durango', 'Ram'],
  Jeep: ['Wrangler', 'Cherokee', 'Grand Cherokee', 'Renegade'],
  Fiat: ['500', 'Panda', '500X'],
  Buick: ['Enclave', 'Regal', 'Encore', 'LaCrosse'],
  GMC: ['Sierra', 'Yukon', 'Terrain', 'Canyon'],
  Cadillac: ['Escalade', 'CTS', 'XT5', 'ATS'],
  Acura: ['MDX', 'RDX', 'TLX', 'ILX'],
  Infiniti: ['QX60', 'Q50', 'QX80', 'QX50'],
  LandRover: ['Defender', 'Discovery', 'Range Rover', 'Evoque'],
  Lincoln: ['Nautilus', 'Aviator', 'Corsair', 'Navigator'],
  
  // Indian car makes and models
  Tata: ['Nexon', 'Altroz', 'Harrier', 'Safari', 'Tiago'],
  Mahindra: ['XUV700', 'Thar', 'Scorpio', 'Bolero', 'Marazzo'],
  MarutiSuzuki: ['Swift', 'Dzire', 'Vitara Brezza', 'Baleno', 'WagonR'],
  HyundaiIndia: ['Creta', 'Venue', 'i20', 'Santro', 'Verna'],
  ToyotaIndia: ['Innova Crysta', 'Fortuner', 'Urban Cruiser', 'Glanza'],
  HondaIndia: ['City', 'Amaze', 'WR-V', 'Jazz'],
  RenaultIndia: ['Kwid', 'Triber', 'Duster', 'Lodgy'],
  NissanIndia: ['Magnite', 'Kicks', 'Sunny'],
  KiaIndia: ['Seltos', 'Sonet', 'Carnival'],
  MGMotorIndia: ['Hector', 'ZS EV', 'Astor'],
  SkodaIndia: ['Octavia', 'Superb', 'Rapid', 'Kushaq'],
  VolkswagenIndia: ['Vento', 'Polo', 'Tiguan', 'Taigun'],
  ForceMotors: ['Force Gurkha', 'Force Traveller'],
  MahindraElectric: ['e2o', 'eVerito', 'e2oPlus'],
  BMWIndia: ['7 Series', 'X1', 'X3', 'X5', 'X7'],
  AudiIndia: ['Q7', 'Q5', 'A4', 'A6'],
  MercedesIndia: ['C-Class', 'E-Class', 'GLA', 'S-Class'],
};